[project]
name = "PyAutoPlugin"
version = "0.1.1"
description = "Windows平台，窗口绑定、图色、Ocr、工具集"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"                  # SPDX 表达式（setuptools>=77）
authors = [{ name = "Qr1mln", email = "593747881@qq.com" }]
classifiers = [
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Testing",
]

dependencies = [
    "mss>=10.2.0",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pywin32>=312; sys_platform == 'win32'",
    "windows-capture>=2.0.1; sys_platform == 'win32'",
    "requests>=2.32.0",
]
[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
pythonpath = ["."]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["PyAutoPlugin*"]
